# LAPP Analysis Workspace

This directory contains pre-processed log data generated by LAPP (Log Auto Pattern Pipeline).

## Files

### raw.log

The original log file, unmodified. Use grep or read specific line ranges to investigate details.

### summary.txt

All discovered log templates, sorted by occurrence count (most frequent first).
Each entry contains:

- **Template ID** (e.g. [D1]) — a stable identifier for this pattern
- **Pattern** — the generalized template where `<*>` replaces variable parts (IPs, block IDs, timestamps, etc.)
- **Occurrence count** — how many log lines matched this template
- **Samples** — up to 3 concrete log lines matching the template

Start here to understand the overall shape of the logs.

### errors.txt

A filtered view of templates and lines containing error-related keywords
(error, warn, fatal, panic, exception, failed, timeout).

Includes two sections:

1. **Matched error templates** — templates whose pattern contains error keywords, with counts and samples
2. **Unmatched error lines** — raw lines containing error keywords that did not match any template (up to 50)

Start here if you are looking for problems.
